### ISSUE TITLE
improve behavior of setting of custom endpoint

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeycomb-opentelemetry-go#105]
follow up from #102 

note: As a follow-up, we should review how endpoints are set because it should not require removal of http://. Also we should make sure it is as easy as possible (and clearly documented) to set the insecure option for similar use cases of sending to an endpoint within the network. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vreynolds** [comment]
`OTEL_EXPORTER_OTLP_INSECURE=true` is honored by the distro

**Comment by JamieDanielson** [comment]
suggestion: fix in launcher for better experience (if http but using grpc, drop the http protocol)... propose issue upstream for better helper function for end user (if http but using grpc, drop the http protocol... OR ignore with logged error and use the default collector endpoint).

**Comment by JamieDanielson** [comment]
Docs have been updated for using the insecure option.

The rest of this issue (footguns with endpoints) are now split into https://github.com/honeycombio/otel-launcher-go/issues/9 and https://github.com/honeycombio/otel-launcher-go/issues/10 on the launcher.
