### ISSUE TITLE
Distro does not honour OTEL_EXPORTER_OTLP_ENDPOINT env var

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/honeycomb-opentelemetry-go#134]
**Versions**
The distro does not use the OTEL_EXPORTER_OTLP_ENDPOINT env var and should. It does use HONEYCOMB_API_ENDPOINT as exepcted.

When fixing, the honeycomb endpoint should have precedence over the OTLP endpoint and if none are provided use the default value.

**Comment by vreynolds** [comment]
Confirmed this is indeed not honoring the `OTEL_EXPORTER_OTLP_ENDPOINT`, I believe [this](https://github.com/honeycombio/honeycomb-opentelemetry-go/blob/5207216b64271032d9e0b4923351843b8f291ff1/honeycomb.go#L50) is the culprit that always overrides anything set in the `OTEL_` env var to use Honeycomb prod.
