### ISSUE TITLE
CI failed to publish github release

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/honeycomb-opentelemetry-go#42]
CI failed to publish a gibhub release.
- https://app.circleci.com/pipelines/github/honeycombio/honeycomb-opentelemetry-go/47/workflows/6ccb9110-ba59-4825-b4a3-a299645b35ee/jobs/48

**Comment by vreynolds** [comment]
was the repo already public when that job ran? if it was still private, that may have been the reason

**Comment by MikeGoldsmith** [comment]
Yep, working now 👍🏻
