### ISSUE TITLE
don't throw error for existing dataset

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeycomb-opentelemetry-go#97]
**Versions**

v0.3.0

**Steps to reproduce**

1. set `HONEYCOMB_DATASET` env var with a non-classic key
2. get error `error setting up OTel SDK - &{%!e(string=Dataset detected! Datasets are a Honeycomb Classic configuration value.
Unset HONEYCOMB_DATASET or remove configuration code that sets a dataset.)}`
3. and then get `exit status 1`

**Additional context**

[This should change](https://github.com/honeycombio/honeycomb-opentelemetry-go/blob/94049e664d272ae36b6871557c19e1a67c8f1650/honeycomb.go#L201) - we want to warn on a dataset not being necessary for traces, but it shouldn't actually cause a problem in the app.

**Comment by cartermp** [comment]
appropros of our discussion around not erroring a lot, I would argue the whole thing should change: https://github.com/honeycombio/honeycomb-opentelemetry-go/blob/94049e664d272ae36b6871557c19e1a67c8f1650/honeycomb.go#L188-L204
